question_data = [
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Clefairy was intended to be Ash's starting Pokémon in the pilot episode of the cartoon.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "No Game No Life first aired in 2014.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In the 'Melancholy of Haruhi Suzumiya' series, the narrator goes by the nickname Kyon.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "Kiznaiver is an adaptation of a manga.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
     "question": "Druid is a mage class in 'Log Horizon'.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In the 'To Love-Ru' series, Golden Darkness is sent to kill Lala Deviluke.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
     "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
     "question": "In the 'Kagerou Daze' series, Shintaro Kisaragi is prominently shown with the color red.",
     "correct_answer": "True", "incorrect_answers": ["False"]}]
